############################################################################################################
# Car section
############################################################################################################
GET http://localhost:3000/Inventory
# GET http://localhost:3000/Inventory/64936a5262804f8bca9213b0

POST http://localhost:3000/Inventory HTTP/1.1
content-type: application/json

{
    "Hybrid": "Leaf, Prius, Volt",
    "Stock": "3",
    "Color": "Black, Blue, Grey"
}

PUT http://localhost:3000/Inventory/64936a5262804f8bca9213b0 HTTP/1.1
content-type: application/json

{
    "Car": "Ferrari, Lamborghini, Porsche",
    "Stock": "3",
    "Color": "White, Blue, Yellow"
} 

DELETE http://localhost:3000/Inventory/649cdf8fd44d272d29457de4 HTTP/1.1

############################################################################################################
# Motorcycle section
############################################################################################################
GET http://localhost:3000/Motorcycle

POST http://localhost:3000/Motorcycle HTTP/1.1
content-type: application/json

{
    "Harley": "Davidson",
    "Color": "Black"
}

PUT http://localhost:3000/Motorcycle/64936b2162804f8bca9213b3 HTTP/1.1
content-type: application/json

{
    "Japanese_Bikes": "8",
    "Color": "Green, Black, Blue"
}

DELETE http://localhost:3000/Motorcycle/649ce154d44d272d29457de5 HTTP/1.1